export enum Endpoins { 
    LOGIN = "user/login",
    REGISTER = "user/register",
    GET_ALL_PRODUCT = "coffee-item/all-coffees",
    GET_COFFEE_LIKED = "user/get-coffee-liked",
    LIKE_COFFEE = "user/like-coffee",
    FIND_USER_LOGIN = "user/user-login",
    UNLIKE_COFFEE = "user/unlike-coffee",
    GET_COFFEE_BY_ID = "coffee-item/get-coffee-id",
    ORDER = "order/order-coffee",
    ADD_ADDRESS = "address/add-address",
    GET_ALL_ADDRESS = "address/all-address",
    GET_USER_LOGIN = "user/user-login",
    GET_WALLET = "wallet/get-wallet",
    CREATE_WALLET = "wallet/create-wallet",
    TOP_UP_WALLET = "wallet/top-up",
    GET_LIST_ORDER = "order/all-orders-user",
    GET_ORDER_BY_ID = "order/get-order-id",
    REVIEW = "review/review-coffee",
    RECEIVED_ORDER = "order/received"
}